# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eed2e2a0f361bb803529156ae1b18311dabe62ffde7340d67a9d4d536690651a0cf208547d748ff5b0e785647047261839fadac5f97edc101225811ffd3583f4

test:
  secret_key_base: 06b800bf7dd5585e4254968d8c8d8666d0b990ef672916d12c1bdd10672ae0b2a808fc3e545d2bf8cbbd07d4399cd3e4e0b7c236dec7f139a0f775feab0b9139

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
